version: '3.3'
services:
  back:
    image: node:16
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: sh -c "npm install &&
       npm install -g @nestjs/cli &&
       npm run start:dev"
    networks:
      - main_network
  video_consumer:
    build: ./video-consumer
    volumes:
      - ./video-consumer/nest-service:/app
    working_dir: /app
    command: sh -c "
       python3.9 /python_script/setup.py &
       npm install &&
       npm install -g @nestjs/cli &&
       npm run start"
    networks:
      - main_network
  text_documents_consumer:
    image: node:16
    volumes:
      - ./text-documents-consumer:/app
    working_dir: /app
    command: sh -c "apt update &&
       apt install poppler-utils antiword -y &&
       npm install &&
       npm install -g @nestjs/cli &&
       npm run start:dev"
    networks:
      - main_network
  redis:
    image: redis
    networks:
        - main_network
networks:
  main_network:
    external: true