version: '3.3'
services:
  back:
    image: node:16
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: sh -c "npm install &&
       npm install -g @nestjs/cli &&
       npm run start:dev"
  video_consumer:
    build: ./video-consumer
    volumes:
      - ./video-consumer/nest-service:/app
    working_dir: /app
    command: sh -c "
       python3.9 /python_script/setup.py &
       npm install &&
       npm install -g @nestjs/cli &&
       npm run start"
  text_documents_consumer:
    image: node:16
    volumes:
      - ./text-documents-consumer:/app
    working_dir: /app
    command: sh -c "npm install &&
       npm install -g @nestjs/cli &&
       npm run start"
  redis:
    image: redis


volumes:
  esdata1:
    driver: local